version: "3.9"

services: 

  db:
    container_name: labor_db 
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - pg-data:/var/lib/postgresql/data


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8888:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD} 
    depends_on:
      - db
  
  backend_app:
    container_name: backend_app
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend/
    volumes:
      - ./backend/:/usr/backend/
    environment:
      - DATABASE_URL=${DATABASE_URL}
    expose:
      - 8000
    ports:
      - 8001:8000
    depends_on:
      - db


volumes:
  pg-data:
